version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = false

[dev.deploy.parameters]
stack_name = "sopt-operation-dev"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
template = "template-dev.yaml"
resolve_s3 = false

[prod.deploy.parameters]
stack_name = "sopt-operation-prod"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
template = "template-prod.yaml"
resolve_s3 = false
